config/routes.rb
Rails.application.routes.draw do
  post 'contributions/create'

  post 'contributions/destroy'
  resources :contributions
  devise_for :users

  resources :posts do 
  	member do
  		get "like", to: "posts#upvote"
  		get "dislike", to: "posts#downvote"
  	end
    resources :comments
  end

  root "posts#index"

  resources :searches
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
	belongs_to :post
	belongs_to :user

	def accept
    	self.accepted = true
  	end

end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable

	validates :title, :content, presence: true

	has_attached_file :image, styles: { medium: "250x250#", small: "200x200#" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	belongs_to :user
	has_many :comments

	# Who wrote the post. BDD foreign key: author_id
	belongs_to :author, class_name: 'User'

	# All requests: Contributions for this post with accepted == false
	has_many :contribution_requests, -> { where(accepted: false) }, class_name: 'Contribution'

	# All accepted contributions: Contributions for this post with accepted == true
	has_many :contributions, -> { where(accepted: true) }

	# Actual contributors: all users with contributions for this post having accepted as true
	has_many :contributors, through: :contributions, source: :user

	def self.search(search)
	  if search
	    where(['name LIKE ?', "%#{search}%"])
	  else
	    all
	  end
	end

	# private

	# def user_quota

	# 	if user.posts.today.count >= 2
	#      errors.add(:base, "Exceeds daily limit")

	# 	elsif user.posts.this_week.count >= 5
	#      errors.add(:base, "Exceeds weekly limit")

	# 	end
	# end

end

app/models/search.rb
class Search < ActiveRecord::Base
	def search_posts

	   posts = Post.all

	   posts = posts.where("title like ?", "%#{keywords}%") if keywords.present?
	   posts = posts.where("title like ?", "%#{title}%") if title.present?

	   return posts
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # All posts written by a user. Inverse of Post#author
  has_many :posts, foreign_key: 'author_id'

  # All requests to contribute to posts
  has_many :contribution_requests, -> { where(accepted: false) }, class_name: 'Contribution'
  # All accepted requests to contribute to posts
  has_many :contributions, -> { where(accepted: true) }

  # All posts the user can contribute to
  has_many :contributed_posts, through: :contributions, source: :post

  has_many :posts do

    def today
      where(:created_at => (Time.zone.now.beginning_of_day..Time.zone.now))
    end

    def this_week
      where(:created_at => (Time.zone.now.beginning_of_week..Time.zone.now))
    end

  end

  has_many :comments

  after_create :send_notification

  def send_notification
  	AdminMailer.new_user(self).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_post, only: [:create]

	def create
		@comments = Comment.create(params[:comment].permit(:body))
	end

	private

	def set_post
      @post = Post.find(params[:post_id])
	end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  def create
  	@contribution = current_user.contributions.build(:user_id => params[:user_id])
  	if @contribution.save
  		flash[:notice] = "Added contributor."
  		redirect_to posts_path(@post)
  	else
  		flash[:error] = "Unable to add contributor."
  		redirect_to posts_path(@post)
  	end
  end

  def destroy
  	@contribution = current_user.contributions.find(params[:id])
  	@contribution.destroy
  		flash[:notice] = "Removed contributor."
  		redirect_to root_url
  	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(['title LIKE ?', "%#{params[:search]}%"])
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @contributions = Contribution.all
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end





  def upvote
    # @post = Post.find(params[:id])
    @post = Post.find(params[:id])
    @post.upvote_by current_user

    RequestedMailer.requested_created(current_user, @post.user, @post.title).deliver

    redirect_to :back

  end




  def downvote
    @post.downvote_by current_user
    cookies[:downvote] = true
    redirect_to :back
  end


  private

    def authenticate
      :authenticate_user! && current_user.try(:admin?)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image, :accepted)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	def new
	   @search = Search.new
	end
	def create
	  @search = Search.create(search_params)
	  redirect_to @search
	end
	def show
	  @search = Search.find(params[:id])
	end

	private	
	def search_params
	   params.require(:search).permit(:keywords, :title)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/comments/_comment.html.erb
<div>
	<p><h3><%= comment.name %></h3>
	Submitted <%= time_ago_in_words(comment.created_at) %> ago</p>
	<%= comment.body %><br>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	 
	 <%= f.label :body %><br>
	 <%= f.text_area :body %><br>
	 <%= f.submit %>

<% end %>

app/views/contributions/create.html.erb
<h1>Contributions#create</h1>
<p>Find me in app/views/contributions/create.html.erb</p>

app/views/contributions/destroy.html.erb
<h1>Contributions#destroy</h1>
<p>Find me in app/views/contributions/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bingo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: "Are your sure?"} %></li>
      </ul>
    <% else %>
	  <ul class="nav navbar-nav navbar-right">
		<li><%= link_to "Signin", new_user_session_path %></li>
		<li><%= link_to "Signup", new_user_registration_path %></li>
	  </ul>
	<% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div>

<div class="container">
  
</div>

	<% if notice %>
	<p class="notice"><%= notice %></p>
	<% end %>
</div>
<div>
	<% if alert %>
	<p class="notice"><%= alert %></p>
	<% end %>

</div>



<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <div class="signin card-container">
        <h3>Create New Project</h3>
    <hr />
<%= form_for @post, :html => { :multipart => true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- upload images with paperclip gem -->
  <div class="field">
    <%= f.file_field :image, class: "form-control", placeholder: "Upload Image" %>
  </div>
  <!-- end -->

  <div class="field">
    <%= f.text_field :title, class: "form-control", placeholder: "Title"  %>
  </div>
  <div class="field">
    <%= f.text_area :content, class: "form-control", placeholder: "Content"  %>
  </div>
  <div class="actions">
    <%= f.submit "Create New Project", class: "btn btn-lg btn-primary btn-block btn-signin"  %>
  </div>
<% end %>

  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/helper.html.erb
<div id="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post_image">
        <%= link_to (image_tag post.image.url(:small)), post_path(post) %>
      </div>
      <div class="post_content">
        <div class="title">
          <h2>
            <%= link_to post.title, post_path(post) %>
          </h2>
        </div>
        <div class="data clearfix">
          <p class="username">
            Shared by
            <%= post.user.name %>
          </p>
          <div class="container">
           <p><%= post.get_upvotes.size %></p>
            <%= link_to "Like", like_post_path(post), method: :get %>

          <% if current_user.try(:admin?)%>
            <%= link_to 'Show', post %>
            <%= link_to 'Edit', edit_post_path(post) %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% else %>
            <%= link_to 'Show', post %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>

<%= link_to "Advanced Search", new_search_path %>

<br />

<div class="container">
  <%= form_tag posts_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
  <% end %>
</div>

<div class="container">
  <%= link_to 'New Project', new_post_path, class: "btn btn-primary btn-block" %>
</div>
<br />
<div class="container">
<div id="posts">
  <div class="row">
  <% @posts.each do |post| %>
      <div class="post col-md-4">
        <div class="post_image">
          <%= link_to (image_tag post.image.url(:small)), post_path(post) %>
        </div>
        <div class="post_content">
          <div class="title">
            <h2>
              <%= link_to post.title, post_path(post) %>
            </h2>
          </div>
          <div class="data clearfix jumbotron">
            <h5>
              Post by
              <%= post.user.name %>
            </h5>
            <h5>
              Project Requests
              <%= post.get_upvotes.size %>
            </h5>
            <div class="wrapper">

            <% if current_user.try(:admin?)%>
              <%= link_to 'Show', post %>
              <%= link_to 'Edit', edit_post_path(post) %>
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% else %>
              <%= link_to "Join Project", like_post_path(post), method: :get, class: "btn btn-primary btn-block" %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
  <% end %>
  </div>
</div>
</div>
</div>
<% else %>

<h1>Listing Posts</h1>

<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<br />

<div class="container">
  <%= link_to 'New Post', new_post_path, class: "btn btn-primary btn-block" %>
</div>
<br />


<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading pin_image">
		<%= image_tag @post.image.url(:medium) %>
    </div>


  <h2>Contributors</h2>

  <% @post.contribution_requests.each do |d| %>
    <%= d.user.name %>
    <%= d.post.contribution_requests.count %>
    <%= d.post.contributions.count %>
    <%= d.post.contributors.count %>
  <% end %>

  <h3>Requests</h3>
  <%= link_to "Contributor",contributions_create_path(user_id = @user), method: :post, class:" btn btn-primary" %>
  <%= @contributions.each do |f| %>
    <%= f.user.name %>
    <%= f.user.email %>
    <%= link_to "Remove", contributions_destroy_path,method: :delete %>
    <br />
  <% end %>

    <div class="panel-body">
      <h1>
        <%= @post.title %>
      </h1>
      <p class="description">
        <%= @post.content %>
      </p>
      </p>
		<%= @post.user.name %>
	  <p>
	  	<p>
		  <strong>Content:</strong>
		  <%= @post.content %>
		</p>
    </div>
    <div class="panel-footer">
      <div class="row">

          <p class="user">
            Requests
			<p><%= @post.get_upvotes.size %></p>
			<hr />
          </p>
          <%= link_to "Join Project", like_post_path(@post), method: :get, class: "btn btn-primary btn-block" %>
        </div>
    </div>
  </div>
</div>

app/views/searches/_show.html.erb
<h1>Search Result</h1>
<% if @search.search_posts.size <= 0 %>
	<p>No Records Found</p>
<% else %>
	<% @search.search_posts.each do |c| %>
		<div>
			<div class="container" >
			<%= image_tag c.image, style: "
			height: 100px;
			width: 100px;"%>
			</div>
			<h1><%= c.title %></h1>
		</div>
	<% end %>
<% end %>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_for @search do |s| %>
  <div class="field">
    <%= s.label :keywords %><br />
    <%= s.text_field :keywords %>
  </div>

  <div class="field">
    <%= s.label :title %><br />
    <%= s.text_field :title %>
  </div>

  <div class="actions"><%= s.submit "Search" %></div>

<% end %>

app/views/searches/show.html.erb
<h1>Search Result</h1>
<% if @search.search_posts.empty? %>
	<p>No Records Found</p>
<% else %>
	<% @search.search_posts.each do |c| %>
		<div>	
			<h1><%= image_tag c.image, style: "
			height: 100px;
			width: 100px;
			"%></h1>
			<p><%= link_to c.title, post_path(@search.search_posts, @post) %></p>
		</div>
	<% end %>
<% end %>